<?php

/**
 * Implements hook_mail().
 */
function event_registration_mail($key, &$message, $params) {

  switch ($key) {

    case 'registration_mail':

      $message['subject'] = 'Event Registration Confirmation';

      $message['body'][] =
        "Hello " . $params['full_name'] . ",\n\n" .
        "You have successfully registered for the event.\n\n" .
        "Event Name: " . $params['event_name'] . "\n" .
        "Event Date: " . date('Y-m-d', $params['event_date']) . "\n" .
        "Category: " . $params['category'] . "\n\n" .
        "Thank you.";

      break;
  }
}

/**
 * Implements hook_theme().
 */
function event_registration_theme($existing, $type, $theme, $path) {
  return [
    'admin_dashboard' => [
      'variables' => [
        'items' => NULL,
        'title' => NULL,
        'count' => NULL,
        'summary' => NULL,
        'export_url' => NULL,
        'pager' => NULL,
      ],
      'template' => 'admin-dashboard',
      'path' => $path . '/templates',
    ],
  ];
}

